// NEXUS theme for Monaco Editor
import type { editor } from 'monaco-editor';

export const NEXUS_THEME_NAME = 'nexus-dark';

export const nexusTheme: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'f8f8f8', background: '0f0f0f' },
    { token: 'comment', foreground: '6a9955', fontStyle: 'italic' },
    { token: 'keyword', foreground: '5dd62c' },
    { token: 'string', foreground: 'd4d4aa' },
    { token: 'number', foreground: 'b5cea8' },
    { token: 'regexp', foreground: 'd16969' },
    { token: 'type', foreground: '4ec9b0' },
    { token: 'class', foreground: '4ec9b0' },
    { token: 'function', foreground: 'dcdcaa' },
    { token: 'variable', foreground: '9cdcfe' },
    { token: 'constant', foreground: '4fc1ff' },
    { token: 'tag', foreground: '5dd62c' },
    { token: 'attribute.name', foreground: '9cdcfe' },
    { token: 'attribute.value', foreground: 'd4d4aa' },
    { token: 'delimiter', foreground: 'a1a1aa' },
    { token: 'delimiter.html', foreground: '808080' },
    { token: 'metatag', foreground: '5dd62c' },
    { token: 'metatag.content.html', foreground: 'd4d4aa' },
    { token: 'attribute.value.html', foreground: 'd4d4aa' },
  ],
  colors: {
    'editor.background': '#0f0f0f',
    'editor.foreground': '#f8f8f8',
    'editorLineNumber.foreground': '#4a4a4a',
    'editorLineNumber.activeForeground': '#5dd62c',
    'editorCursor.foreground': '#5dd62c',
    'editor.selectionBackground': '#5dd62c33',
    'editor.inactiveSelectionBackground': '#5dd62c22',
    'editor.selectionHighlightBackground': '#5dd62c22',
    'editor.lineHighlightBackground': '#1a1a1a',
    'editor.lineHighlightBorder': '#00000000',
    'editorIndentGuide.background': '#1a1a1a',
    'editorIndentGuide.activeBackground': '#2a2a2a',
    'editorWhitespace.foreground': '#1a1a1a',
    'editorBracketMatch.background': '#5dd62c22',
    'editorBracketMatch.border': '#5dd62c66',
    'editorGutter.background': '#0f0f0f',
    'editorError.foreground': '#ef4444',
    'editorWarning.foreground': '#f59e0b',
    'editorInfo.foreground': '#5dd62c',
    'editorHint.foreground': '#5dd62c',
    'scrollbarSlider.background': '#5dd62c22',
    'scrollbarSlider.hoverBackground': '#5dd62c33',
    'scrollbarSlider.activeBackground': '#5dd62c44',
    'minimap.background': '#0a0a0a',
    'editorWidget.background': '#1a1a1a',
    'editorWidget.border': '#5dd62c22',
    'editorSuggestWidget.background': '#1a1a1a',
    'editorSuggestWidget.border': '#5dd62c33',
    'editorSuggestWidget.foreground': '#f8f8f8',
    'editorSuggestWidget.selectedBackground': '#5dd62c22',
    'editorSuggestWidget.highlightForeground': '#5dd62c',
    'list.hoverBackground': '#5dd62c11',
    'list.activeSelectionBackground': '#5dd62c22',
    'list.inactiveSelectionBackground': '#5dd62c11',
    'input.background': '#1a1a1a',
    'input.border': '#5dd62c33',
    'input.foreground': '#f8f8f8',
    'focusBorder': '#5dd62c66',
  },
};

export function defineNexusTheme(monacoInstance: typeof import('monaco-editor')) {
  monacoInstance.editor.defineTheme(NEXUS_THEME_NAME, nexusTheme);
}
